### ISSUE TITLE
Very slow binding phase

### ISSUE THREAD

**Issue by Gama11** [detekt/detekt#8611]
Testing out 2.0.0-alpha.0, some of our modules are taking a lot of time to analyze, and that time is dominated by the binding phase - over 5 minutes in this example:

```diff
2025-09-05T11:36:39.690+0200 [INFO] [system.out] Phase LoadConfig took 19.157156ms
2025-09-05T11:36:39.691+0200 [INFO] [system.out] Phase CreateSettings took 1.322825251s
2025-09-05T11:36:39.691+0200 [INFO] [system.out] Phase ValidateConfig took 55.431897ms
2025-09-05T11:36:39.691+0200 [INFO] [system.out] Phase Parsing took 34.761us
-2025-09-05T11:36:39.691+0200 [INFO] [system.out] Phase Binding took 5m 27.293048973s
2025-09-05T11:36:39.691+0200 [INFO] [system.out] Phase LoadingExtensions took 7.486400ms
-2025-09-05T11:36:39.691+0200 [INFO] [system.out] Phase Analyzer took 13.936989472s
2025-09-05T11:36:39.691+0200 [INFO] [system.out] Phase Reporting took 29.036972ms
```

Even "quick" runs are dominated by the binding phase:

```diff
2025-09-05T11:57:40.846+0200 [QUIET] [system.out] Phase LoadConfig took 13.359856ms
2025-09-05T11:57:40.846+0200 [QUIET] [system.out] Phase CreateSettings took 1.627701053s
2025-09-05T11:57:40.846+0200 [QUIET] [system.out] Phase ValidateConfig took 22.335442ms
2025-09-05T11:57:40.846+0200 [QUIET] [system.out] Phase Parsing took 9.604us
-2025-09-05T11:57:40.847+0200 [QUIET] [system.out] Phase Binding took 32.789184976s
2025-09-05T11:57:40.847+0200 [QUIET] [system.out] Phase LoadingExtensions took 10.978958ms
-2025-09-05T11:57:40.847+0200 [QUIET] [system.out] Phase Analyzer took 11.929906224s
2025-09-05T11:57:40.847+0200 [QUIET] [system.out] Phase Reporting took 122.422605ms
```

This is with latest Kotlin (2.2.10) and Gradle (9.0.0).

**Comment by BraisGabin** [comment]
The Binding phase should be reduced by a lot once https://github.com/detekt/detekt/pull/8513 is merged. With that merged we should be able to remove all the legacy type solving engine.

That should reduce the Binding time in a half.

**Comment by 3flex** [comment]
@Gama11 can you please take a measure and report with 1.23.8 for comparison?

**Comment by Gama11** [comment]
It seems like this phase timing output did not exist in that version? However, `gradle detektMain detektTest --continue --debug --rerun-tasks` takes around 4 minutes 30 seconds for the entire multi-module project with 1.23.8 (83 modules, 105 kLoC), which is less than the binding phase of that single module in the first example.

**Comment by BraisGabin** [comment]
> It seems like this phase timing output did not exist in that version?

It should. These timing aren't new.

**Comment by Gama11** [comment]
Ah, it seems like an explicit `debug = true` is needed in the `detekt {}` block. With v2 the `--debug` was enough IIRC.

It looks like the slowest binding phase out of any of the modules with 1.23.8 is around 40 seonds:

```
2025-09-22T10:47:12.470+0200 [INFO] [system.out] Phase LoadConfig took 28ms
2025-09-22T10:47:12.473+0200 [INFO] [system.out] Phase CreateSettings took 0s
2025-09-22T10:47:12.473+0200 [INFO] [system.out] Phase ValidateConfig took 21ms
2025-09-22T10:47:12.473+0200 [INFO] [system.out] Phase Parsing took 1.321s
2025-09-22T10:47:12.473+0200 [INFO] [system.out] Phase Binding took 39.109s
2025-09-22T10:47:12.475+0200 [INFO] [system.out] Phase LoadingExtensions took 7ms
2025-09-22T10:47:12.479+0200 [INFO] [system.out] Phase Analyzer took 2.618s
2025-09-22T10:47:12.479+0200 [INFO] [system.out] Phase Reporting took 87ms
```

**Comment by BraisGabin** [comment]
#8675 should aliviate this problem. But I'm not sure if it will fix this issue. The time difference is huge.

Once merged we need to check again the time difference.

**Comment by Gama11** [comment]
Giving this another try with 2.0.0-alpha.1, at first it looked like things haven't improved at all or even gotten worse (had a bunch of detektMain tasks seemingly not making much progress, running for 20+ minutes until I stopped the build).

However, invoking Gradle with `--no-parallel` seems to improve things massively, the entire multi-module project finishes within 3 min 30 secs. I'm not entirely sure what's going on here, maybe I need to play around with `org.gradle.workers.max` or how much memory I give Gradle (currently `org.gradle.jvmargs=-Xmx2g`).

**Comment by eduardb** [comment]
@Gama11 Do you have `detekt.use.worker.api=true` in your `gradle.properties` by any chance? I noticed that with the worker API enabled, Detekt runs out of memory, and then the whole tasks just hangs indefinitely. Setting it to `false` fixes this issue for me.

**Comment by Gama11** [comment]
I'm starting to question what `org.gradle.parallel=true` accomplishes in the first place, it doesn't really seem to improve build speeds even for regular builds (`gradle assemble testClasses`), and it still seems to be running tasks from many subprojects in parallel without it.

@eduardb No, I didn't have that configured. Interestingly, after explicitly setting that to false, I noticed the following output, not sure if I just missed that in previous builds or if that somehow only shows up now:

```
The Daemon will expire after the build after running out of JVM heap space.
The project memory settings are likely not configured or are configured to an insufficient value.
The daemon will restart for the next build, which may increase subsequent build times.
These settings can be adjusted by setting 'org.gradle.jvmargs' in 'gradle.properties'.
The currently configured max heap space is '2 GiB' and the configured max metaspace is 'unknown'.
For more information on how to set these values, please refer to https://docs.gradle.org/9.1.0/userguide/build_environment.html#sec:configuring_jvm_memory in the Gradle documentation.
To disable this warning, set 'org.gradle.daemon.performance.disable-logging=true'.
Daemon will be stopped at the end of the build after running out of JVM heap space
```

**Comment by Gama11** [comment]
This definitely seems to be memory-related, with a generous `org.gradle.jvmargs=-Xmx12g`, detekt tasks don't hang anymore. However, it still took around a minute longer than a non-parallel run (4 min 30 sec). Not sure if that's just regular variance or parallelization overhead (or still not enough memory) - I was using `--rerun-tasks` to ensure the times are somewhat comparable / independent of caching etc.

**Comment by Gama11** [comment]
Actually, I do have `parallel = true` in the `detekt {}`  gradle block. Not sure how that relates to / if that's the same as `detekt.use.worker.api=true`?

**Comment by 3flex** [comment]
> Actually, I do have `parallel = true` in the `detekt {}`  gradle block. Not sure how that relates to / if that's the same as `detekt.use.worker.api=true`?

They're different. Worker API uses Gradle's worker API support but detekt's support for it has always been experimental.

detekt's parallel mode runs a few things internally in parallel. It shouldn't cause massive changes in performance.

**Comment by 3flex** [comment]
RE: org.gradle.parallel, this is Gradle's parallel support. If you're already using configuration cache I don't believe it has any effect as CC supersedes it, which might explain why you don't see differences when that flag is enabled or not.

Agree that the most likely issue is memory, see https://github.com/detekt/detekt/issues/8116

**Comment by kaltenbrunner** [comment]
I'm running into this issue as well. Increasing memory results in only marginal performance improvements.

From what I can tell, this is related to detekt running diagnostics on each file individually, which was introduced in commit d1e992dc54fff787baa0d11ebe2e9e54c7c6802d. With detekt now using the Analysis API, is the binding phase (and diagnostics) still needed?

There's also a related comment from a while back: https://github.com/detekt/detekt/pull/8675#discussion_r2377192563

**Comment by 3flex** [comment]
> There's also a related comment from a while back: #8675 (comment)

My comment there still stands:

> We could remove these checks, put them behind a flag, or only run if in debug mode.

All have tradeoffs. There's one other option, which is to force anyone writing rules to check KaCallInfo to see if a call has been resolved successfully or not.

The reason these checks were added was because people sometimes had issues with false positives caused by semantic information used by detekt being incorrect. This was caused by incorrect classpath being passed to detekt.

With analysis API there's only one way I'm aware of to check for diagnostics reported on entire files which is what's been implemented. This also means we lose the benefit of AA being lazy since we process all files anyway.

Ultimately we really probably only care about failed call resolution and we could narrow things to check for that only, which would be lazy and more performant, but less comprehensive.

**Comment by BraisGabin** [comment]
I'm wondering. Should we create a new cli option (and a gradle task too) that would check that the classpath is correct?

We know that this check is really expensive so doing it on every run is not a good idea. But we could have a gradle task that anyone could run to check those errors and fix them. In my project I would create a nighly pipeline to run that task to ensure that nothing is broken.

This task will also help us with the false positives for missing information. We could ask the reporter "please run `detektWhatever` does it passes?".

**Comment by KatieBarnett** [comment]
> detekt's parallel mode runs a few things internally in parallel. It shouldn't cause massive changes in performance.

I actually have found that it makes a big difference, I'm running 2.0.0-alpha.2 and when I include `parallel = true`, type resolution tasks take forever, with it set to `false` the same task takes under 3 minutes. I have been using `--rerun-tasks` to compare runs. `--no-parallel` has little to no effect.

**Comment by 3flex** [comment]
@Gama11 @kaltenbrunner are you using parallel mode?

**Comment by BraisGabin** [comment]
I guess that parallel mode consumes too much ram. And probably on gradle with little benefits. You already have all the cores working.

Maybe we should remove that option from the gradle plugin.

**Comment by kaltenbrunner** [comment]
@3flex I've tested with and without `--parallel`. There's no real difference in performance.

**Comment by 3flex** [comment]
We'd need more data but based on this anecdotal evidence parallel mode is at worst much slower and at best makes no difference in performance.

This suggests it should be removed or at least come with a bigger warning if used.

**Comment by FletchMcKee** [comment]
@BraisGabin This milestone issue may be fixed with #9127. @Gama11 You’ll want to verify with the latest snapshot, but I was seeing similar binding phase numbers that are much faster now after that PR.

**Comment by BraisGabin** [comment]
Can someone else confirm this?

**Comment by njuro** [comment]
I can confirm it's much faster when using snapshot after this PR. But I've been getting this error randomly, don't know if related (may be actually Kotlin 2.3.20 bug):

```
ERROR: kotlinx/coroutines/internal/intellij/IntellijCoroutines
java.lang.NoClassDefFoundError: kotlinx/coroutines/internal/intellij/IntellijCoroutines
        at com.intellij.concurrency.ThreadContext.installThreadContext$lambda$8(threadContext.kt:291)
        at com.intellij.concurrency.ThreadContext.withThreadLocal(threadContext.kt:353)
        at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:289)
        at com.intellij.util.concurrency.Propagation$capturePropagationContext$$inlined$Runnable$1.run(Runnable.kt:15)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:369)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:649)
        at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.internal.intellij.IntellijCoroutines
        ... 11 more
ERROR: Worker exited due to exception
java.lang.AssertionError: kotlinx/coroutines/internal/intellij/IntellijCoroutines
        at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:90)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:439)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:289)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:372)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:649)
        at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.lang.NoClassDefFoundError: kotlinx/coroutines/internal/intellij/IntellijCoroutines
        at com.intellij.concurrency.ThreadContext.installThreadContext$lambda$8(threadContext.kt:291)
        at com.intellij.concurrency.ThreadContext.withThreadLocal(threadContext.kt:353)
        at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:289)
        at com.intellij.util.concurrency.Propagation$capturePropagationContext$$inlined$Runnable$1.run(Runnable.kt:15)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:369)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.internal.intellij.IntellijCoroutines
        ... 11 more
Exception in thread "ApplicationImpl pooled thread 14" java.lang.AssertionError: Worker exited due to exception
        at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:90)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:426)
        at com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor.afterExecute(AppScheduledExecutorService.java:164)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1093)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:649)
        at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.lang.AssertionError: kotlinx/coroutines/internal/intellij/IntellijCoroutines
        at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:90)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:439)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:289)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:372)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
        ... 3 more
Caused by: java.lang.NoClassDefFoundError: kotlinx/coroutines/internal/intellij/IntellijCoroutines
        at com.intellij.concurrency.ThreadContext.installThreadContext$lambda$8(threadContext.kt:291)
        at com.intellij.concurrency.ThreadContext.withThreadLocal(threadContext.kt:353)
        at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:289)
        at com.intellij.util.concurrency.Propagation$capturePropagationContext$$inlined$Runnable$1.run(Runnable.kt:15)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:369)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.internal.intellij.IntellijCoroutines
        ... 11 more
```

**Comment by BraisGabin** [comment]
Closing as this issue is solved. 

> But I've been getting this error randomly, don't know if related (may be actually Kotlin 2.3.20 bug):

Please, open a new issue for this.

**Comment by njuro** [comment]
@BraisGabin any estimation for new Detekt 2 (alpha) release that would include the changes introduced in https://github.com/detekt/detekt/pull/9127? They were so significant we opted for using `SNAPSHOT` release for now, but that's not ideal long-term.

**Comment by BraisGabin** [comment]
I can't give any estimation here. AFAIK we are waiting for #9100.

**Comment by eygraber** [comment]
I'll compile the full results later, but I benchmarked 2.0.0-alpha.3 with parallel enabled/disabled and enabled seems to be 3-5% faster.
