### PR TITLE
Update to Kotlin 2.0.0

### LINKED ISSUE #6715: K2 compiler crashes Detekt
## Expected Behavior
After updating our project to use K2 compiler we expect we don't get a crash when we run `detekt`

## Observed Behavior
In our project when we run detekt we are getting similar exceptions to this one:
```
> Exception while analyzing expression in (135,15) in //Forlago/modules/feature-foo/src/main/kotlin/com/leinardi/forlago/feature/foo/ui/foo/FooScreen.kt

  Attachments:
  causeThrowable
  java.lang.IllegalArgumentException: fromIndex(1) > toIndex(0)
        at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
        at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
        at org.jetbrains.kotlin.builtins.FunctionTypesKt.getValueParameterTypesFromFunctionType(functionTypes.kt:178)
....
```

## Steps to Reproduce
1. Update your project to use K2 compiler. To achieve that you have to update your `gradle.properties` file adding:

```
# K2
android.experimental.lint.version=8.3.0-alpha17
android.lint.useK2Uast=true
kapt.use.k2=true
kotlin.experimental.tryK2=true
```
2. Run `detekt` and we are getting several exceptions similar to:
```
> Task :modules:feature-debug:detektDebug FAILED
ERROR: Exception while analyzing expression in (200,11) in //Users/javierarroyo/Projects/Personal/Forlago/modules/feature-debug/src/main/kotlin/com/leinardi/forlago/feature/debug/ui/DebugScreen.kt

Attachments:
causeThrowable
java.lang.IllegalArgumentException: fromIndex(1) > toIndex(0)
        at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
        at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
        at org.jetbrains.kotlin.builtins.FunctionTypesKt.getValueParameterTypesFromFunctionType(functionTypes.kt:178)
        at org.jetbrains.kotlin.resolve.FunctionDescriptorResolver.getValueParameters(FunctionDescriptorResolver.kt:380)
```

### Github example
You can find a project sample with the issue here:
- https://github.com/leinardi/Forlago/pull/48

## Your Environment

* Version of detekt used: 1.23.4
* Version of Gradle used (if applicable): 8.5
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: Mac OS Monterey - v12.7.1
* Link to your project (if it's a public repository): https://github.com/leinardi/Forlago/pull/48

### PR DESCRIPTION
**Pull request by 3flex**
Fixes #6715

This is safe to release with alpha/beta dependencies in my opinion. poko 0.16.0-beta01 is based on Kotlin 2.0.0-RC3 which is the same as 2.0.0. kctfork is only used in tests.

### CODE REVIEW

**Comment by jarroyoesp** [comment]
Hey @3flex after trying the commit https://github.com/detekt/detekt/commit/429a178210acb52a976219f14b12c7d2d37665a6 as you mentioned here https://github.com/detekt/detekt/issues/6715#issuecomment-1863819743. I've been able to compile your branch and generate the library on my MavenLocal. But when I've run `detekt` in my project, I am getting the following errors:

```
> Task :build-conventions:compileKotlin FAILED
e: Pre-release classes were found in dependencies. Remove them from the classpath, recompile with a release compiler or use '-Xskip-prerelease-check' to suppress errors
e: file:///Users/javierarroyo/Projects/Personal/Forlago/build-conventions/build/generated-sources/kotlin-dsl-accessors/kotlin/gradle/kotlin/dsl/accessors/_2fb462c0d2ba107f613d15985247d494/Accessors32ikgp1isdd8mwexzgbe6rirl.kt:65:44 Class 'io.gitlab.arturbosch.detekt.extensions.DetektExtension' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
```
Thanks :)

**Comment by 3flex** [comment]
You probably need to follow steps here: https://docs.gradle.org/8.3/release-notes.html#kotlin_k2

**Comment by 3flex** [comment]
I wouldn't expect this to get merged to `main` until Kotlin 2 final is released - I don't recall ever supporting new Kotlin versions in snapshots while in beta/RC phase. It's also not backwards compatible, and new fixes in beta5 will mean some workarounds in this branch will be reverted.

It also relies on a snapshot version of poko.

I'm glad it's working well, and thank you for testing, but it's not ready to be merged.

**Comment by 3flex** [comment]
It really depends what the change is. This PR/branch is intended only to introduce support for Kotlin 2/K2 so any changes you want to make to this branch would need to support that goal. You'd said it's already working well, so I'm not sure what you'd want to change?

Any other changes for detekt should be raised as separate PRs.

I'll rebase this branch on `main` when new Kotlin 2.0.0 releases are made so it will stay fairly current. For everything else I'd suggest merging the other way - keep your own branch and occasionally rebase on top of this branch.

I'm sorry but beyond that I can't provide much help, you can try stack overflow to ask questions about git usage.

**Review by BraisGabin — APPROVED** [review]
🎉

**Comment by 3flex** [comment]
If this is cherry picked into the 1.x branch, these PRs will also need to be merged:
* #7302 
* #7303

**Comment by nebffa** [comment]
Kotlin 2.0 has just been released. I see this has been merged - are you planning to publish a release relatively soon? :)

**Comment by 3flex** [comment]
I haven't made releases previously so I can't say, but you can try snapshots until a new one is pushed out.

**Comment by TWiStErRob** [comment]
@cortinico are you planning a patch with Kotlin 2.0.0 support? (current 1.23.6 works, but I would assume that the K2 improvements propagate to compiler-embedded, so a detekt patch/minor release could benefit from a 2x speed improvement?)

**Comment by cortinico** [comment]
> @cortinico are you planning a patch with Kotlin 2.0.0 support? (current 1.23.6 works, but I would assume that the K2 improvements propagate to compiler-embedded, so a detekt patch/minor release could benefit from a 2x speed improvement?)

I was thinking we can cut a `2.0.0-alpha-01` or so from the main branch to overcome this. Wdyt @TWiStErRob @3flex ?

**Comment by TWiStErRob** [comment]
It feels like that might be a long way away (from stable), there are still breaking changes coming in refractors, right? So alpha would require some to migrate again and again, and therefore I personally wouldn't actually use the alpha in a live project (e.g. at work) and miss out on speed of a stable compiler. I think @3flex can comment on the complexity of cherry, based on the above comment it's 3 small PRs, however with one of them forcing language version, does it mean we wouldn't benefit from K2's improvements?

**Comment by 3flex** [comment]
Language version 1.9 limitation applies to compiler plugin only. The CLI and Gradle in theory get speedups but I haven't tested anything.

Cherry picking sounds like a good plan.

**Comment by karolgil** [comment]
Looking forward to using `detekt` in a project using Kotlin 2.0, happy to be a guinea pig.

Do you see any chances of publishing alpha or even a safe snapshot version for testing? Or maybe you have a timeline for when that might happen?

**Comment by baseballyama** [comment]
I have successfully updated my company’s project to Kotlin 2.0, including the compiler plugin. However, we are currently blocked by detekt not supporting Kotlin 2.0.
I’m concerned that the longer detekt lacks support for Kotlin 2.0, the fewer users and new adopters we will attract.
Is there a way we can release a version that supports Kotlin 2.0?
Please let me know if there’s anything I can do to assist.

**Comment by BraisGabin** [comment]
detekt WORKS with Kotlin 2.0. If it doesn't work for you then it's probably an issue in your configuration. If you need help you can use the discussions.

**Comment by karolgil** [comment]
Interesting.

I simply added `id("io.gitlab.arturbosch.detekt") version "1.23.6"` to the `plugins` section of my `build.gradle.kts`. Now when I try running `./gradlew detekt` I'm seeing the following:
```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :detekt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detekt'.
> Invalid value (22) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 30s
1 actionable task: 1 executed
```

This matches the problem raised in https://github.com/detekt/detekt/issues/7382, for which the solution was apparently this PR that I don't think was released yet?

**Comment by 3flex** [comment]
You can use snapshot versions until there's a new release that has Kotlin 2 built in to get around the JVM issue.

The compiler plugin works with Kotlin 2 but only currently only if the language version is 1.9 and lower. That gap is tracked in #7304.

**Comment by baseballyama** [comment]
@BraisGabin 

> detekt WORKS with Kotlin 2.0

Does this mean it works with the snapshot version? Or does it also support version 1.23.6?
If you mean support is only in the snapshot version, could you backport this PR to 1.23.6 and release 1.23.7? (Or rather, can I send the patch myself?)
As the number of users of the snapshot version increases, we expect more complaints about temporary breakages and destructive changes in the main branch. Users do not want to be affected by these issues. (I'm sorry if this concern didn’t exist.😅)

**Comment by BraisGabin** [comment]
The current stable version of detekt works with kotlin 2.0

**Comment by karolgil** [comment]
> The current stable version of detekt works with kotlin 2.0

To recap, because I think I'm just not expressing my issues correctly - `detekt` works with Kotlin 2.0, it doesn't work with language versions higher than 1.9 and that won't be solved until https://github.com/detekt/detekt/issues/7304 is merged and released.

In the meantime the best bet for folks in my situation is to build and use a snapshot version.

Is that correct?

**Comment by TWiStErRob** [comment]
@karolgil I think the compiler and detekt language versions don't have to match, because there are no new language features in 2.0, unless you're using the compiler plugin, which is not the default when you use Detekt Gradle Plugin as far as I know. Other than the Java 22 issue, are you facing actual problems using detekt 1.23.6 in a Kotlin 2 project?

**Comment by BraisGabin** [comment]
> Or does it also support version 1.23.6?

I use 1.23.6 with kotlin 2.0 without any problem. So, what I mean, is that the church stable version of detekt already supports kotlin 2.0.

**Comment by baseballyama** [comment]
> I use 1.23.6 with kotlin 2.0 without any problem. So, what I mean, is that the church stable version of detekt already supports kotlin 2.0.

Now I can also use detekt 1.23.6 with Kotlin 2.0, but I need to use Kotlin v1 for detekt.
Is this the same situation as yours, @BraisGabin?

This is my `gradle.kts` configuration.
```kt
project.afterEvaluate {
    configurations.matching { it.name == "detekt" }.all {
        resolutionStrategy.eachDependency {
            if (requested.group == "org.jetbrains.kotlin") {
                useVersion("1.9.23")
            }
        }
    }
}
```

**Comment by BraisGabin** [comment]
I don't use spring boot so I don't need that. But yes. That's expected.

**Comment by karolgil** [comment]
I got it to work.

Initially I was following [the getting started documentation](https://detekt.dev/docs/gettingstarted/gradle) but today I decided to take a look at [the README](https://github.com/detekt/detekt?tab=readme-ov-file#with-gradle). After adding the following
```
tasks.withType<Detekt>().configureEach { jvmTarget = "21" }
```
the `./gradlew detekt` worked and listed all issues found in the project.

I guess I don't have to understand the details of it but I'm still confused as to why that's needed.
Kudos to @baseballyama because that code sample was a good pointer to try to fiddle with jvm settings for detekt.

**Comment by BraisGabin** [comment]
> I guess I don't have to understand the details of it but I'm still confused as to why that's needed.

That is not longer needed on detekt 2.0 (current SNAPSHOT). But for 1.0 you need to set up that. Also, if there is anything in the documentation that isn't clear, please, could you open a PR updating it so the next one doesn't find the same issue?

**Comment by shuhuang-faire** [comment]
Hi, is the snapshot version also recommended for ruleset maintainers? I see quite some compilation errors after upgrading from 1.23.6 to main-SNAPSHOT. Just wonder if we should fix these errors now or wait until the stable release is out.

**Comment by BraisGabin** [comment]
The apis are still not stable so they can still change.

But, it would be great if you can update and provide us feedback about how the new apis feel.

**Comment by shuhuang-faire** [comment]
Thanks Brais. If we use the snapshot version, it would be best to stick to a specific date to prevent our pipeline from breaking due to unexpected API changes. I noticed that the earliest version in the snapshot repository is from 8/28. Does the repository have a short retention period?

**Comment by cortinico** [comment]
> Does the repository have a short retention period?

That depends on Sonatype's retention period (we don't control it)

**Comment by shuhuang-faire** [comment]
Thanks. Do you have a rough estimate when we can expect a stable version of it?

**Comment by cortinico** [comment]
> Thanks. Do you have a rough estimate when we can expect a stable version of it?

We're going to release this in 1.23.7 as soon as we fix the last remaining issues we have with the CI
